apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platforminvitation-emailtemplate.yaml
  - userapproved-emailtemplate.yaml
  - userinvitation-emailtemplate.yaml
  - userpasskeyadded-emailtemplate.yaml
  - userrejected-emailtemplate.yaml
  - usersuspicious-emailtemplate.yaml
  - userwaitlist-emailtemplate.yaml
  - userwelcome-emailtemplate.yaml
