name: Publish Kustomize Bundle

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - 'config/email-templates/**'
  release:
    types:
      - published

jobs:
  publish-kustomize-bundle:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@2dbca23d057e20ff1aab144b94a06d09ea75e5f6 # v1.21.0
    with:
      bundle-name: ghcr.io/datum-cloud/email-templates-kustomize
      bundle-path: config/email-templates
    secrets: inherit
